# Generated by Django 4.1.4 on 2023-01-09 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0004_galeria_author_photo_author_alter_galeria_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 9, 11, 31, 18, 328188, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=450)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 11, 31, 18, 330188, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.photo')),
            ],
        ),
    ]
